name: "Pull Request"
description: please replace "prefix" with one of the ones listed below
title: "prefix: "
labels: ["documentation", "bug"]
body:
- type: html
  attributes:
    value: |
        <base href="/mypage/ladeda/" />
        ...
        <a href="1/">(goes to http://domain.com/mypage/ladeda/1/)</a>

- type: checkboxes
  id: type
  attributes:
    label: Operating System
    description: Which OS are you running LibreWolf on?
    options:
    - label: audio
    - label: gfx
    - label: models
    - label: quakec
    - label: NixOS
    - label: wads Linux
    - label: BSD
    - label: wip

- type: textarea
  id: description
  attributes:
    label: Description
    description: Please describe the bug clearly.
  validations:
    required: true
